[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline'; script-src-elem 'self' https://*.netlify.com https://unpkg.com; font-src 'self' 'unsafe-inline' data:; img-src 'self' 'unsafe-inline' blob: data:; connect-src 'self' blob: data: ; media-src 'self'; object-src; frame-ancestors 'none'; form-action 'self'; base-uri 'self'"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=15768000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"